---
- name: elasticsearch | install xfsprogs
  apt:
    name: xfsprogs
    update_cache: yes
    state: latest

- name: elasticsearch | make filesystem
  filesystem:
    fstype: xfs
    dev: "{{ es_mount_point }}"

- name: elasticsearch | get disk UUID
  shell: blkid -s UUID -o value {{ es_mount_point }}
  register: UUID

- name: elasticsearch | fstab entry
  mount:
    path: "{{ es_mount_dir }}"
    src: UUID="{{ UUID.stdout }}"
    fstype: xfs
    opts: noatime
    state: mounted
