---
- name: elasticsearch | install xfsprogs
  apt:
    name: xfsprogs
    update_cache: yes
    state: present

- name: elasticsearch | make filesystem
  filesystem:
    fstype: xfs
    dev: "{{ es_mount_point }}"

- name: elasticsearch | fstab entry
  mount:
    path: "{{ es_mount_dir }}"
    src: "{{ es_mount_point }}"
    fstype: xfs
    opts: noatime
    state: mounted
